### ISSUE TITLE
microphone not working

### ISSUE THREAD

**Issue by LinkTheFox** [googlecreativelab/chrome-music-lab#13] opened 2018-02-10 15:00 UTC
despite allowing the microphone it still says it isn't allowed it means some of the features cannot be used because there is no microphone feature i don't know if its just my laptop of your website playing up but please fix it

**Comment by cmwhitejr** [comment] 2018-02-18 14:56
I'm having the same problem - microphone still inactive despite "allowing" it and making sure the mic is working properly on the Systems Preferences.  Restarted both Chrome and my Mac after selecting the "allow" mic option on Chrome.

**Comment by Rebecca333** [comment] 2018-02-18 15:15
I'm also having the same problem - I have my microphone "allowed" on Chrome, made sure it worked in the System Preferences, reset all of my settings, turned on pop-ups, removed all of my extensions, scanned Chrome and my whole computer for anything that might be interfering, downloaded and tried the website with all of the above on Google Canary, turned off "Use hardware acceleration when available.", and restarted my Chrome multiple times.

**Comment by hellobabs** [comment] 2018-02-18 19:44
We are aware of this issue and hope to have a new version up in march with this fixed. Thank you for your feedback.

**Comment by cmwhitejr** [comment] 2018-02-18 19:57
Thank you for the quick response . . . Do you know if the problem is isolated to Macs using Chrome?

Do you know if the same problem exists on PCs running Windows and Chrome?


On Feb 18, 2018, at 2:44 PM, hellobabs <notifications@github.com> wrote:

We are aware of this issue and hope to have a new version up in march with this fixed. Thank you for your feedback.

**Comment by hellobabs** [comment] 2018-02-18 20:20
Can you specify the exact mac you are on and chrome version please? We are
right in the middle of addressing this may be best to wait until our next
release, but letting me know the exact set up you are using will help.

**Comment by hellobabs** [comment] 2018-02-18 20:22
And also what experiment. Thank you.

**Comment by cmwhitejr** [comment] 2018-02-18 21:59
We are using version 10.13.3 High Sierra and the most recent update for Chrome on two 2013 & 2016 MacBook Airs and a 2015 MacBook Pro - all having the same problem.

This is happening for the Spectrogram and the Voice Spinner, which are the two experiments that we need to use for a Science Fair project.

We found a way to make this work though – starting up a Mac in Windows 7 using Bootcamp, however that is running Windows on a Mac.

We would prefer being able to use all our Macs in “OS-mode” instead of just using one Mac that has a partitioned hard drive in Windows-mode.

When will the March update come out?  Early-March?  Mid-March?  Late-March?

The Science Fair is in mid-March, so if this could be solved by early-March, it would be greatly appreciated.

Using a Mac in Windows-mode sucks battery life big time and there is no power sources at any of the Science Fair Exhibit booths.

Thank you,

Charlie White


On Feb 18, 2018, at 3:22 PM, hellobabs <notifications@github.com> wrote:

And also what experiment. Thank you.

**Comment by hellobabs** [comment] 2018-02-18 22:37
Thanks Charlie for the details.

Bear with me as we are in the midst of many projects and hoping to update
music lab as well. I will provide more info later this week. The goal is
early March + an additional experiment added.

So we will do our best and I can help guide you to the best performing +
(least annoying) set up for your science fair.

**Comment by cmwhitejr** [comment] 2018-02-18 23:57
The good news is that the Windows on Mac option will work for my daughter’s Science Fair project if the Mac update is not ready.

Will you be sending out a notification blast when the update is complete?

If so, please add me (charlesmwhite@verizon.net) to the blast list.

Thanks - and good coding luck with the many projects!


On Feb 18, 2018, at 5:37 PM, hellobabs <notifications@github.com> wrote:

Thanks Charlie for the details.

Bear with me as we are in the midst of many projects and hoping to update
music lab as well. I will provide more info later this week. The goal is
early March + an additional experiment added.

So we will do our best and I can help guide you to the best performing +
(least annoying) set up for your science fair.

**Comment by hellobabs** [comment] 2018-02-19 19:49
Charlie we won't be sending an email blast but I will try and remember to ping this chain once fixed! If not feel free to ping this again to check in. 

I'm pretty confident we will have this fixed in time for your daughters science fair. 

-Catherine

**Comment by cmwhitejr** [comment] 2018-02-20 15:18
Thank you, Catherine.

My daughters and I are looking forward to the update.

Charlie


On Feb 19, 2018, at 2:49 PM, hellobabs <notifications@github.com> wrote:

Charlie we won't be sending an email blast but I will try and remember to ping this chain once fixed! If not feel free to ping this again to check in.

I'm pretty confident we will have this fixed in time for your daughters science fair.

-Catherine

**Comment by cmwhitejr** [comment] 2018-03-09 05:01
Hello Catherine,

The fix must have been made since the microphone now works using the Mac version.

Many Thanks (and Relief!)

Charlie

**Comment by cmwhitejr** [comment] 2018-03-27 22:36
Hello Catherine,

You will be pleased to hear that my daughter Theresa was one of five 5th graders (out of 46) awarded with the CNY STEM Fair's "Highest Honors" designation - and the Chrome Music Lab's Spectrogram played a big part in the success of her project.

![20180325_120759](https://user-images.githubusercontent.com/36601617/37998670-7f7741be-31ed-11e8-9942-e5595dfbc244.jpg)

![20180326_065920](https://user-images.githubusercontent.com/36601617/37998696-a1e19128-31ed-11e8-94cc-ad6c013fb816.jpg)

Thank you for your advocacy in getting the mic problem fixed.

Charlie White

**Closed** 2019-03-18 20:10 UTC
